name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ main, master, develop]
  pull_request:


inputs:
  JAVA_VERSION:
    description: 'Java version to use'
    required: false
    default: '17'
  JAVA_DISTRIBUTION:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: |
          cd simple-api-student
          mvn clean verify